name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: 'minor'
      - name: Alias New tag to VERSION
        run: echo "::set-env name=VERSION::${{ steps.version_bump.outputs.new_tag }}"
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onepanel/core
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          buildargs: VERSION
          tags: ${{ steps.version_bump.outputs.new_tag }}, latest
      - name: Set Slack Message
        run: echo "::set-env name=SLACK_MESSAGE::Version $VERSION. Docker Tag onepanel/core:$VERSION"
      - name: Notify Slack Channels
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: dev
          SLACK_ICON: https://avatars1.githubusercontent.com/u/30390575?s=48&v=4
          SLACK_TITLE: New Core Version
          SLACK_USERNAME: opBot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}


